# NumPy Basics

In this tutorial, you will become familiar with the use of numpy. NumPy is an open source project aiming to enable numerical computing with Python. It was created in 2005, building on the early work of the Numeric and Numarray libraries. It is a powerful library that offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, among others. Most importantly for this course, it provides support for large, multi-dimensional arrays and matrices, along with its large collection of high-level mathematical functions to operate on these arrays. 

Before getting started with NumPy, let us first introduce the concept of libraries.

## 1. Libraries
A Python library is a collection of functions and methods that allows you to perform many actions without writing your own code. To make use of a given library you need to import it.

### Different ways to importing a library
To import libraries use
```python
import library_name
```

If you want to refer to the library using a custom name you can use the reserved word as ...

```python
import library_name as abbreviation_you_want
```

To call a function inside a library write library_name.function_name(parameters) (or if you have used an abbreviation abbreviation_you_want.function_name(parameters))

If you want to import only some functions or modules within the library use

```python
from library_name import function_name1, function_name2
```

## 2. NumPy: The Basics
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes. NumPy’s array class is called `ndarray`. It is also known by the alias `array`.

**Examples:** Run the cells below

In [ ]:
import numpy as np #Importing numpy and using np as its alias

oneD_array = np.array([1,2,3])
print('The array', oneD_array, 'has', oneD_array.ndim, 'dimension, with elements of type ') #The attribute ndim allows to obtain the axes (dimensions) of an array
print('The elements of ', oneD_array, 'are of type', oneD_array.dtype) #dtype provides information about the type of the elements in the array

In [ ]:
twoD_array = np.arange(15).reshape(3, 5) #We create a range from 0 to 14, i.e. a sequence, and we rearrange them in a 2D array of 3 x 5
twoD_array

In [ ]:
print('This array has', twoD_array.ndim, 'dimensions, with shape', twoD_array.shape) #Shape tells us about the dimensions of the array

### Creating arrays
`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on. 

Some examples:

In [ ]:
array_from_seq = np.array([1.5, 2, 3])
print('This is an array from a sequence (ndim=', array_from_seq.ndim,')', array_from_seq)

In [ ]:
array_from_seq_seq = np.array([(1.5, 2, 3), (4, 5, 6)])
print('This is an array from a sequence of sequences (ndim=', array_from_seq_seq.ndim,')')
array_from_seq_seq

In [ ]:
array_from_seq_seq_seq = np.array([[(1.5, 2, 3), (4, 5, 6)], [(1.5, 2, 3), (4, 5, 6)]], dtype=complex) # We have specified the type of the elements as complex
print('This is an array from a sequence of sequences of sequences (ndim=', array_from_seq_seq_seq.ndim,')')
array_from_seq_seq_seq

By default, NumPy will creat an array as of dtype `float64`. However, as we saw in the previous example, it is possible to specify the dtype during the array creation, by using the reserved word `dtype` in the constructor.

Alternatively, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

**Examples:**

In [ ]:
np.zeros((2, 2))

In [ ]:
np.ones((2, 3, 4), dtype=np.int16)

In [ ]:
np.empty((3, 3))

### Reshaping Arrays
An array has a shape given by the number of elements along each axis. This can be be changed with various commands. Some of these will return an array with the new shape, whereas othere will modify *in place* the current array.

**Methods that do not change the shape in-place:** These are `ravel`, `reshape` and the property `T`. Examples:

In [ ]:
A = np.array([[1, 1, 2], [0, 1, 0], [3, 2, 1], [5, 5, 5]])
A

In [ ]:
print('ravel flattens the array')
A.ravel()

In [ ]:
print('reshape returns the array with a modified shape')
A.reshape(2, 6)

In [ ]:
print('A.T returns the array transposed')
A.T

**Methods that change the shape in-place:** This is `resize`. Examples:

In [ ]:
B = np.array([[1, 1, 2], [0, 1, 0], [3, 2, 1], [5, 5, 5]])
print('B:',B)

print('After resize:')
B.resize((2, 6))
B

## 3. Basic Operations
Arithmetic operators on arrays apply elementwise. The result of the operation is a newly created array.

**Examples:**

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([5, 6, 7, 8])

c = a - b
d = a + b
e = 2*a
f = a > 25
g = a * b
h = a / b
print('a - b =', c)
print('a + b =', d)
print('2 * a =', e)
print('a > 25 =', f)
print('a * b =', g)
print('a / b =', h)

Operators such as `+=` or `*=` are an exception. They modify *in-place* the array without generating a new one.

**Example:**

In [ ]:
a *= 3
a

In [ ]:
b -= 4
b

### Matrix multiplication
Unlike other common languages operating on matrices (e.g. Matlab), the product operator `*` operates elementwise in NumPy arrays, as in the previous example.
The matrix product can be performed using the `@` operator (Python >=3.5) or the `dot` function :

In [ ]:
A = np.array([[1, 1], [0, 1]])
B = np.ones((2,2))
            
A * B  #Element-wise multiplication

In [ ]:
A @ B #Matrix multiplication

In [ ]:
A.dot(B) #Using the dot product function is an alternative to matrix multiplication

### Exercise 1
Generate a 1D array of length 10 of powers of 2, i.e. $[2^0, 2^1, ..., 2^9]$.

You **should not** generaete it *manually*

In [ ]:
#Your code in this block
pows = None #Replace None with your code

print(f'pows:\n{pows}\n')

## 4. Functions
Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [ ]:
A = np.array([
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
    ])

print('Sum of elements in A', A.sum())
print('Min value in A', A.min())
print('Max value in A', A.max())

By specifying the axis parameter you can apply an operation along the specified axis of an array:

In [ ]:
print('Sum of elements in A axis 0', A.sum(axis=0))
print('Min value in A axis 1', A.min(axis=1))
print('Max value in A axis 1', A.max(axis=1))

### Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (`ufunc`). These functions operate elementwise on an array, producing an array as output.

In [ ]:
from math import pi

logarithm=np.log(A) #Log function
sinusoidal=np.sin(2*pi*A) #sinusoidal
squared_root=np.sqrt(A) #squared root

B = 10*A
AB_sum = np.add(A,B) #Sum of two arrays can also be done through a function

print('log(A):', logarithm)
print('sin(2*pi*A):', sinusoidal)
print('sqrt(A):', squared_root)
print('add(A,B):', AB_sum) 
print('is equivalent to A + B', A + B)

This is a summary of the universal functions available:

<img src="./images/all_universal.PNG" width="900">
For further information about NumPy's functions, visit the official documentation.

### Exercise 2
1. Create a one dimensional array that goes from 0 to 10 in steps 0f 0.1. Store this array in a variable named x. Hint: Check the documentation of the NumPy function arange()
2. Create an array as $\sin \left(\dfrac{2*\pi * x}{2} \right)$. 
   Store it in a variable named y.
3. Place your code in the cell below and execute it
4. Execute the cell after your code. If your code works you should see a plot like this:

<img src="./images/sinusoidal.PNG" width="500">


In [ ]:
# Your code here
x = 
y = 

In [ ]:
#Execute this cell. You should see the plot, if your code works.
import matplotlib.pyplot as plt

plt.plot(x,y)
plt.show()

### Linear Algebra
The most common linear algebra operators which will may use during the course for vectors (1D arrays) and matrices (2D arrays):

* `np.matmul` - Scalar product, vector-matrix or matrix-matrix multiplication (very similar to np.dot).
* `@` - The same as np.matmul.
* `np.linalg.inv` - Matrix inversion.
* `np.linalg.norm` - Norm computation (L2 norm by default).
* `np.linalg.solve` - Numerically stable solution to a system of linear equations given as Ax = b.
* `x.T` - Transposition.

**Examples:**

In [ ]:
## Matrix multiplication.
m1 = np.eye(3)
m2 = np.random.uniform(-10., 10., (3, 8))
m_mult = m1 @ m2

m_mult_2 = np.matmul(m1,m2)

print(f'First multiplication:\n{m_mult}\n')
print(f'Second multiplication:\n{m_mult_2}\n')

m2_trans = m2.T

print(f'M2:\n{m2}\n')
print(f'M2 transposed:\n{m2_trans}\n')

## 5. Array Indexing
Numpy proposes multiple ways to access the elements of an array. 

### Slicing
Slincing in NumPy has the same behavior as in python lists. It means taking elements from one given index to another given index.

* To select a slice instead of an index : `[start:end]`.
* It is also possible to define the step: `[start:end:step]`
* If the start is not defined is considered `0`
* If the end is not defined is considered  length of array in that dimension
* If the step is not defined is considered `1`
* If negative values are used the count starts from the last element in the given dimension


In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.arange(1,13).reshape(3, 4) 

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

# Slice taking one element every 2 elements.
c = a[::2,::2]
print(c) #prints [[1 3] [9 11]]

d = a[-1:,] #prints [[ 9 10 11 12]]
print(d)

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. 

In [ ]:
a = np.arange(1,13).reshape(3, 4) 

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)" 

### Array of Indices
NumPy allows for providing a list of integer indices for every axis.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of array of indices is equivalent to the following integer indexing:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using array of indices, you can reuse the same# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous iarray of indices example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

**Example:** Selecting and mutating one element from each row of a matrix

In [ ]:
# Create a new array from which we will select elements
a = np.arange(1,13).reshape(4, 3) 

print(a)  # prints "[[ 1,  2,  3],
          #         [ 4,  5,  6],
          #         [ 7,  8,  9],
          #         [10, 11, 12]]"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

### Masking 
Another way to indexing is bt using boolean arrays representing a binary mask. The mask needs to have the same shape as the indexed array, or it must match along the first dimensions (where the last dimensions are taken as is). A boolean array can only contain boolean values `True` and `False`.

Frequently this type of indexing is used to select the elements of an array that satisfy some condition. 

In [ ]:
a = np.arange(1,13).reshape(3, 4) 
print(a) 
# prints [[ 1  2  3  4]
#         [ 5  6  7  8]
#         [ 9 10 11 12]]

# Creating the mask manually.
mask = np.zeros((3, 4), dtype=bool)
mask[0, 1:4] = True
mask[2, 2] = True
mask[-2, -2:] = True
print(mask) #prints [[False  True  True  True]  [False False True true]  [False False  True  False]]

print(a[mask]) #prints array([ 2,  3,  4,  7,  8, 11])

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# The same procedure can be done through a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

### Structural indexing
NumPy introduces an object np.newaxis and an ellipsis syntax to facilitate indexing/reshaping.
* NewAxis - `np.newaxis` can be used within square brackets to create a new empty axis. It is equivalent to using a None instead.
* ellipsis - this operator which is written `...` stands for "as many as needed" consecutive symbols `:` used when slicing a multidimensional array.

In [ ]:
#np.newaxis
col_vec = np.array([1, 2, 3])
print(col_vec)
print(col_vec.shape) #prints (3, )

new_col_vec = col_vec[:, np.newaxis]  # or col_vec[:, None]
print(new_col_vec.shape) #prints (3, 1)

#This can be done equally as
newer_col_vec =  col_vec[:, None]
print(newer_col_vec.shape) #prints (3, 1)

print(new_col_vec) # prints [[1]
                   #         [2]
                   #         [3]]

In [ ]:
x = np.ones((3, 4, 5, 6))

x[0,3,3,3] =10 #Mutation of an element in x
print(x.shape) # prints (2, 3, 4, 5)

a = x[0, :, :, 3]
b = x[0, ..., 3] #equivalent to the above expression

print(a.shape) #print (4, 5)
print(b.shape) #print (4, 5)

np.allclose(a,b) #allclose returns True if two arrays are element-wise equal within a tolerance. The tolerance values are positive, typically very small numbers.

### Exercise 3
Using the slicing and indexing techniques seen so far, extract the blue, red and green subarrays as per the figure below.

<img src="./images/slicing_exercise.PNG" width="250">

In [ ]:
full_array = np.arange(30).reshape(6, 5) + 1
print(full_array)
#blue_sub_array = #Your code here
#red_sub_array = #Your code here
#green_sub_array = #Your code here

In [ ]:
full_array = np.arange(30).reshape(6, 5) + 1
print(f'Matrix:\n{full_array}\n')

blue_sub_array = None #Replace with your code
print(f'blue:\n{blue_sub_array}\n')


red_sub_array = None #Replace with your code
print(f'red:\n{red_sub_array}\n')


green_sub_array = None #Replace with your code
print(f'green:\n{green_sub_array}\n')

# Bonus: Come up with indexing which selects from the original matrix the following submatrix:
# [[29, 28], 
#  [9, 8]]

bonus_sub_array = None #Replace with your code
print(f'bonus:\n{bonus_sub_array}\n')

# Check the results:
assert(np.allclose(blue_sub_array, np.array([[1, 5], [6, 10], [11, 15], [16, 20], [21, 25], [26, 30]])))
assert(np.allclose(red_sub_array, np.array([[8, 9], [18, 19], [28, 29]])))
assert(np.allclose(green_sub_array, np.array([12, 13, 14])))
assert(np.allclose(bonus_sub_array, np.array([[29, 28], [9, 8]])))

## 6. Iterating
An ND array can be expressed as a list of N-1 dimensional arrays.

For instance, a 3D array `x` can be though as a list of 2D matrices, where the first matrix can be access via `x=[0,:,:]` or equivalently `x[0]`.

By conceiving an array as a list of arrays, we can use what we know about iterating over lists using `for` or `while` loops.

In [ ]:
# Let us create a 3D array, iterate through it's slices, i.e. matrices, and 
# find the trace of every matrix.
x = np.random.uniform(0, 10, (5, 10, 10))

for i, matrix in enumerate(x):
    print(f'Trace of matrix {i}: {np.trace(matrix)}')

**Important:** In many cases, it is best to avoid using the `for` and `while` loops as they are not very fast. Where possible, the use of vectorization should be prefered as it achieves the same results, while being much faster.

## 7. Other Resources
The web is full of resources and tutorials about NumPy. A good starting point can be:

1. NumPy basics: https://docs.scipy.org/doc/numpy/user/basics.html
2. Official NumPy tutorial: https://docs.scipy.org/doc/numpy/user/quickstart.html
